apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elfin-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elfin-service
            port:
              number: {{ .Values.service.port }}
