---
apiVersion: v1
kind: Service
metadata:
  name: elfin-service
  labels:
    app: elfin-app
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
    name: http
  selector:
    app: elfin-app
